"""Add walking_shape column to stop_correspondence table.

Revision ID: 034
Revises: 033
Create Date: 2026-01-28

Stores cached pedestrian route shapes generated by BRouter.
Format: JSON array of [lat, lon] coordinates.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034_add_walking_shape_to_correspondence'
down_revision = '033_add_raptor_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('stop_correspondence', sa.Column('walking_shape', sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column('stop_correspondence', 'walking_shape')
