#!/usr/bin/env python3
"""Populate local_holidays table with city-specific holidays for Spain.

This script adds local holidays (festivos locales) for major Spanish cities.
These are holidays that only apply to specific municipalities.

Usage:
    python scripts/populate_local_holidays.py
    python scripts/populate_local_holidays.py --clear  # Clear existing and repopulate
"""

import argparse
import logging
from core.database import SessionLocal
from src.gtfs_bc.holiday.infrastructure.models import LocalHolidayModel

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


# Local holidays by province and city
# Format: (province_code, city, name, month, day)
# Province codes are derived from first 3 letters of province name (uppercase)
# as generated by import_province_boundaries.py
LOCAL_HOLIDAYS = [
    # Madrid (MAD)
    ("MAD", "Madrid", "San Isidro", 5, 15),
    ("MAD", "Madrid", "Virgen de la Almudena", 11, 9),
    ("MAD", "Alcalá de Henares", "Santos Niños", 8, 6),
    ("MAD", "Getafe", "Virgen de los Angeles", 8, 2),
    ("MAD", "Móstoles", "Nuestra Señora de los Santos", 9, 12),
    ("MAD", "Leganés", "Virgen de Butarque", 9, 11),
    ("MAD", "Fuenlabrada", "San Esteban", 12, 26),
    ("MAD", "Alcorcón", "San Jorge", 4, 23),
    ("MAD", "Parla", "Nuestra Señora de la Soledad", 9, 10),
    ("MAD", "Torrejón de Ardoz", "San Isidro", 5, 15),

    # Barcelona (BAR)
    ("BAR", "Barcelona", "La Mercè", 9, 24),
    ("BAR", "Hospitalet de Llobregat", "Santa Eulalia", 2, 12),
    ("BAR", "Badalona", "Sant Anastasi", 5, 11),
    ("BAR", "Terrassa", "Sant Pere", 6, 29),
    ("BAR", "Sabadell", "Fiesta Mayor", 9, 7),
    ("BAR", "Mataró", "Les Santes", 7, 27),
    ("BAR", "Santa Coloma de Gramenet", "Santa Coloma", 12, 31),
    ("BAR", "Cornellà de Llobregat", "Sant Ildefons", 1, 23),
    ("BAR", "Sant Boi de Llobregat", "Santa Maria", 9, 8),
    ("BAR", "Granollers", "L'Ascensió", 5, 29),  # Variable

    # Valencia (VAL)
    ("VAL", "Valencia", "San Vicente Ferrer", 4, 14),  # Variable: Monday after Easter week
    ("VAL", "Valencia", "San Dionisio", 10, 9),

    # Alicante (ALI)
    ("ALI", "Alicante", "San Juan", 6, 24),
    ("ALI", "Elche", "Virgen de la Asunción", 8, 14),
    ("ALI", "Torrevieja", "Virgen del Carmen", 7, 16),
    ("ALI", "Orihuela", "Virgen de Monserrate", 9, 8),
    ("ALI", "Benidorm", "Virgen del Sufragio", 11, 15),
    ("ALI", "Alcoy", "San Jorge", 4, 23),

    # Castellón (CAS)
    ("CAS", "Castellón de la Plana", "Magdalena", 3, 22),  # Variable

    # Sevilla (SEV)
    ("SEV", "Sevilla", "San Fernando", 5, 30),
    ("SEV", "Dos Hermanas", "Santa Ana y Santiago", 7, 26),
    ("SEV", "Alcalá de Guadaíra", "San Mateo", 9, 21),
    ("SEV", "Utrera", "Virgen de Consolación", 9, 8),

    # Zaragoza (ZAR)
    ("ZAR", "Zaragoza", "San Valero", 1, 29),
    ("ZAR", "Zaragoza", "Cincomarzada", 3, 5),
    ("ZAR", "Calatayud", "San Roque", 8, 16),
    ("ZAR", "Utebo", "San Lamberto", 4, 17),

    # Málaga (MÁL)
    ("MÁL", "Málaga", "Virgen de la Victoria", 9, 8),
    ("MÁL", "Marbella", "San Bernabé", 6, 11),
    ("MÁL", "Vélez-Málaga", "San Miguel", 9, 29),
    ("MÁL", "Fuengirola", "Virgen del Rosario", 10, 7),
    ("MÁL", "Torremolinos", "San Miguel", 9, 29),
    ("MÁL", "Benalmádena", "Virgen de la Cruz", 9, 14),
    ("MÁL", "Estepona", "Virgen del Carmen", 7, 16),
    ("MÁL", "Ronda", "Romería de la Virgen de la Cabeza", 6, 11),

    # Murcia (MUR)
    ("MUR", "Murcia", "Bando de la Huerta", 4, 8),  # Variable: Tuesday after Easter
    ("MUR", "Cartagena", "Virgen de la Caridad", 11, 1),
    ("MUR", "Lorca", "Virgen de las Huertas", 9, 8),

    # Vizcaya/Bizkaia (VIZ)
    ("VIZ", "Bilbao", "Santiago Apóstol", 7, 25),
    ("VIZ", "Bilbao", "Virgen de Begoña", 10, 11),
    ("VIZ", "Getxo", "Andra Mari", 8, 15),
    ("VIZ", "Barakaldo", "Virgen del Carmen", 7, 16),
    ("VIZ", "Portugalete", "Virgen de la Guía", 9, 9),

    # Guipúzcoa/Gipuzkoa (GUI)
    ("GUI", "Donostia-San Sebastián", "Virgen del Coro", 8, 15),
    ("GUI", "Donostia-San Sebastián", "San Sebastián", 1, 20),
    ("GUI", "Irun", "San Marcial", 6, 30),

    # Álava (ÁLA)
    ("ÁLA", "Vitoria-Gasteiz", "Virgen Blanca", 8, 5),
    ("ÁLA", "Vitoria-Gasteiz", "San Prudencio", 4, 28),

    # A Coruña (ACO)
    ("ACO", "A Coruña", "María Pita", 8, 26),
    ("ACO", "Santiago de Compostela", "Apóstol Santiago", 7, 25),
    ("ACO", "Ferrol", "San Julián", 1, 7),

    # Pontevedra (PON)
    ("PON", "Vigo", "Reconquista", 3, 28),
    ("PON", "Pontevedra", "San Blas", 2, 3),

    # Ourense (OUR)
    ("OUR", "Ourense", "San Martín", 11, 11),

    # Lugo (LUG)
    ("LUG", "Lugo", "San Froilán", 10, 5),

    # Asturias (AST)
    ("AST", "Oviedo", "San Mateo", 9, 21),
    ("AST", "Gijón", "Nuestra Señora de Begoña", 8, 15),
    ("AST", "Avilés", "San Agustín", 8, 28),

    # Cantabria (CAN)
    ("CAN", "Santander", "Santiago Apóstol", 7, 25),
    ("CAN", "Torrelavega", "Virgen Grande", 8, 15),

    # Valladolid (VAL2) - Note: collision with Valencia, using full prefix
    ("VAL", "Valladolid", "San Pedro Regalado", 5, 13),

    # Salamanca (SAL)
    ("SAL", "Salamanca", "San Juan de Sahagún", 6, 12),

    # Burgos (BUR)
    ("BUR", "Burgos", "San Lesmes", 1, 30),

    # León (LEÓ)
    ("LEÓ", "León", "San Froilán", 10, 5),

    # Palencia (PAL)
    ("PAL", "Palencia", "San Antolín", 9, 2),

    # Zamora (ZAM)
    ("ZAM", "Zamora", "San Pedro", 6, 29),

    # Ávila (ÁVI)
    ("ÁVI", "Ávila", "Santa Teresa", 10, 15),

    # Segovia (SEG)
    ("SEG", "Segovia", "San Frutos", 10, 25),

    # Soria (SOR)
    ("SOR", "Soria", "San Saturio", 10, 2),

    # La Rioja (LAR)
    ("LAR", "Logroño", "San Bernabé", 6, 11),

    # Navarra (NAV)
    ("NAV", "Pamplona", "San Fermín", 7, 7),
    ("NAV", "Tudela", "Santa Ana", 7, 26),

    # Huesca (HUE)
    ("HUE", "Huesca", "San Lorenzo", 8, 10),
    ("HUE", "Jaca", "Santa Orosia", 6, 25),

    # Teruel (TER)
    ("TER", "Teruel", "San Fernando", 5, 30),

    # Tarragona (TAR)
    ("TAR", "Tarragona", "Santa Tecla", 9, 23),
    ("TAR", "Reus", "Sant Pere", 6, 29),

    # Lleida (LLE)
    ("LLE", "Lleida", "Sant Anastasi", 5, 11),

    # Girona (GIR)
    ("GIR", "Girona", "Sant Narcís", 10, 29),
    ("GIR", "Figueres", "Santa Creu", 5, 3),

    # Cádiz (CÁD)
    ("CÁD", "Cádiz", "Nuestra Señora del Rosario", 10, 7),
    ("CÁD", "Jerez de la Frontera", "Virgen de la Merced", 9, 24),
    ("CÁD", "Algeciras", "Virgen de la Palma", 8, 15),
    ("CÁD", "San Fernando", "Virgen del Carmen", 7, 16),

    # Córdoba (CÓR)
    ("CÓR", "Córdoba", "Nuestra Señora de la Fuensanta", 9, 8),

    # Granada (GRA)
    ("GRA", "Granada", "Virgen de las Angustias", 9, 15),
    ("GRA", "Motril", "Virgen de la Cabeza", 6, 11),

    # Huelva (HUE) - Note: collision with Huesca
    ("HUE", "Huelva", "Fiestas Colombinas", 8, 3),

    # Jaén (JAÉ)
    ("JAÉ", "Jaén", "Virgen de la Capilla", 6, 11),
    ("JAÉ", "Linares", "San Agustín", 8, 28),

    # Almería (ALM)
    ("ALM", "Almería", "Virgen del Mar", 8, 21),
    ("ALM", "El Ejido", "San Isidro", 5, 15),

    # Badajoz (BAD)
    ("BAD", "Badajoz", "San Juan", 6, 24),
    ("BAD", "Mérida", "Santa Eulalia", 12, 10),

    # Cáceres (CÁC)
    ("CÁC", "Cáceres", "San Jorge", 4, 23),
    ("CÁC", "Plasencia", "San Fulgencio", 1, 16),

    # Ciudad Real (CIU)
    ("CIU", "Ciudad Real", "Virgen del Prado", 8, 15),
    ("CIU", "Puertollano", "Virgen de Gracia", 9, 8),

    # Guadalajara (GUA)
    ("GUA", "Guadalajara", "Virgen de la Antigua", 9, 8),

    # Cuenca (CUE)
    ("CUE", "Cuenca", "San Mateo", 9, 21),

    # Toledo (TOL)
    ("TOL", "Toledo", "Corpus Christi", 6, 19),  # Variable
    ("TOL", "Talavera de la Reina", "San Isidro", 5, 15),

    # Albacete (ALB)
    ("ALB", "Albacete", "Virgen de los Llanos", 9, 8),
    ("ALB", "Hellín", "Virgen del Rosario", 10, 7),

    # Santa Cruz de Tenerife (SAN)
    ("SAN", "Santa Cruz de Tenerife", "Virgen de la Candelaria", 2, 2),
    ("SAN", "La Laguna", "Santísimo Cristo", 9, 14),

    # Las Palmas (LAS)
    ("LAS", "Las Palmas de Gran Canaria", "San Pedro Mártir de Verona", 4, 29),

    # Baleares/Illes Balears (BAL or ILL)
    ("BAL", "Palma de Mallorca", "San Sebastián", 1, 20),
    ("BAL", "Ibiza", "Santa María", 8, 5),
    ("BAL", "Mahón", "Virgen de Gracia", 9, 8),

    # Ceuta (CEU)
    ("CEU", "Ceuta", "Virgen de África", 8, 5),
    ("CEU", "Ceuta", "Nuestra Señora del Valle", 9, 8),

    # Melilla (MEL)
    ("MEL", "Melilla", "Virgen de la Victoria", 9, 8),
    ("MEL", "Melilla", "Día de Melilla", 9, 17),
]


def populate_local_holidays(db, clear_existing: bool = False) -> dict:
    """Populate local_holidays table with city-specific holidays.

    Args:
        db: Database session
        clear_existing: If True, delete all existing records before inserting

    Returns:
        Dictionary with statistics
    """
    stats = {
        'deleted': 0,
        'inserted': 0,
        'skipped': 0,
    }

    if clear_existing:
        deleted = db.query(LocalHolidayModel).delete()
        stats['deleted'] = deleted
        db.commit()
        logger.info(f"Deleted {deleted} existing local holidays")

    # Get existing holidays to avoid duplicates
    existing = set()
    for h in db.query(LocalHolidayModel).all():
        existing.add((h.province_code, h.city, h.month, h.day))

    # Insert new holidays
    for province_code, city, name, month, day in LOCAL_HOLIDAYS:
        key = (province_code, city, month, day)
        if key in existing:
            stats['skipped'] += 1
            continue

        holiday = LocalHolidayModel(
            province_code=province_code,
            city=city,
            name=name,
            month=month,
            day=day,
        )
        db.add(holiday)
        stats['inserted'] += 1
        existing.add(key)

    db.commit()

    return stats


def main():
    parser = argparse.ArgumentParser(
        description='Populate local_holidays table with city-specific holidays'
    )
    parser.add_argument(
        '--clear',
        action='store_true',
        help='Clear existing holidays before populating'
    )
    args = parser.parse_args()

    db = SessionLocal()
    try:
        stats = populate_local_holidays(db, clear_existing=args.clear)

        logger.info("\n" + "=" * 50)
        logger.info("Local Holidays Population Summary")
        logger.info("=" * 50)
        logger.info(f"Deleted: {stats['deleted']}")
        logger.info(f"Inserted: {stats['inserted']}")
        logger.info(f"Skipped (already exist): {stats['skipped']}")
        logger.info("=" * 50)

        # Show distribution by province
        logger.info("\nHolidays by province:")
        results = db.query(
            LocalHolidayModel.province_code,
            db.func.count(LocalHolidayModel.id).label('count')
        ).group_by(
            LocalHolidayModel.province_code
        ).order_by(
            db.func.count(LocalHolidayModel.id).desc()
        ).all()

        for row in results:
            logger.info(f"  {row.province_code}: {row.count} holidays")

        logger.info("\nLocal holidays population completed successfully")

    except Exception as e:
        logger.error(f"Error: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
