-- Update cor_tranvia for TRAM_BARCELONA stops
-- Generated from OSM data 2026-01-26
BEGIN;
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Alfons el Magnànim' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Auditori | Teatre Nacional' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Auditori/Teatre Nacional' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Avinguda de Xile' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Besòs' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2' WHERE name = 'Bon Viatge' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Ca l''Aranyó' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Ca n''Oliveres' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Campus Diagonal-Besòs' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Can Clota' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Can Jaumandreu' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Can Rigal' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T2' WHERE name = 'Centre Miquel Martí i Pol' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Ciutadella | Vila Olímpica' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Ciutadella|V.O.' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2' WHERE name = 'Cornellà Centre' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'El Maresme' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2' WHERE name = 'El Pedró' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5' WHERE name = 'Encants de Sant Adrià' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Ernest Lluch' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Espronceda' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4,T6' WHERE name = 'Estació St.Adrià' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4,T6' WHERE name = 'Estació de Sant Adrià' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Fluvià' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2' WHERE name = 'Fontsanta | Fatjó' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2' WHERE name = 'Fontsanta|Fatjó' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Francesc Macià' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Fòrum' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4,T5,T6' WHERE name = 'Glòries' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5' WHERE name = 'Gorg' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T3' WHERE name = 'Hospital SJD|TV3' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T3' WHERE name = 'Hospital Sant Joan Despí | TV3' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2' WHERE name = 'Ignasi Iglésias' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'L''Illa' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5' WHERE name = 'La Catalana' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T2' WHERE name = 'La Fontsanta' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T6' WHERE name = 'La Mina' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'La Sardana' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2' WHERE name = 'Les Aigües' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T2' WHERE name = 'Llevant - Les Planes' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T2' WHERE name = 'Llevant-L.Planes' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Maria Cristina' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Marina' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Montesa' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Monumental' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Numància' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Palau Reial' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Parc del Besòs' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Pere IV' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Pius XII' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Pont d''Esplugues' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4,T6' WHERE name = 'Port Fòrum' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T3' WHERE name = 'Rambla de Sant Just' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T3' WHERE name = 'Sant Feliu | Consell Comarcal' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T3' WHERE name = 'Sant Feliu|C.C.' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5' WHERE name = 'Sant Joan Baptista' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Sant Martí de Provençals' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5' WHERE name = 'Sant Roc' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Selva de Mar' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Sicilia' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Sicília' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T3' WHERE name = 'Torreblanca' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T4' WHERE name = 'Verdaguer' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T3' WHERE name = 'Walden' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Wellington | UPF' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T5,T6' WHERE name = 'Wellington|UPF' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Z.Universitària' AND id LIKE 'TRAM_BARCELONA%';
UPDATE gtfs_stops SET cor_tranvia = 'T1,T2,T3' WHERE name = 'Zona Universitària' AND id LIKE 'TRAM_BARCELONA%';
COMMIT;
